# https://editor.swagger.io/
swagger: "2.0"
info:
  description: "Piggymetrics sample application API"
  version: "1.0.0"
  title: "Swagger Piggymetrics"
  termsOfService: ""
  contact:
    email: "ssundaram1000@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/v1"
tags:
- name: "account"
  description: "Access to Piggymetrics accounts"
schemes:
- "https"
- "http"
paths:
  /api/v1/accounts:
    post:
      tags:
      - "account"
      summary: "Add a new account"
      description: ""
      operationId: "addAccount"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Account object that needs to be added to the application"
        required: true
        schema:
          $ref: "#/definitions/Account"
      responses:
        "201":
          description: "Created"      
        "400":
          description: "Bad Request"
    put:
      tags:
      - "account"
      summary: "Updates an account"
      description: ""
      operationId: "updateAccount"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Account object that needs to be updated"
        required: true
        schema:
          $ref: "#/definitions/Account"
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"
        "404":
          description: "Not Found"
  /api/v1/accounts/{name}:
    get:
      tags:
      - "account"
      summary: "Get account by name"
      description: "Returns a single account"
      operationId: "getAccountByName"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        description: "Name of user owning the account to be returned"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Account"
        "404":
          description: "Not found"


definitions:
  Account:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      lastSeen:
        type: "string"
      note:
        type: "string"
externalDocs:
  description: "Find out more about Piggymetrics"
  url: "http://localhost"